#!/usr/bin/env bash
# update-sha256.sh - Generate SHA256 checksums and update run-remote-steps.sh

set -euo pipefail

echo "=== Generating SHA256 checksums for warning and clean scripts ==="
echo ""

# Generate checksums for all warning and clean scripts across all platforms
declare -A checksums

# Define platforms that have install scripts
PLATFORMS=("cloudzy" "framework" "framework-dual")

for platform in "${PLATFORMS[@]}"; do
  echo "Processing $platform platform..."
  for file in "$platform/install"/*-warnings.sh "$platform/install"/*-clean.sh; do
    if [[ -f "$file" ]]; then
      checksum=$(shasum -a 256 "$file" | cut -d' ' -f1)
      basename_file=$(basename "$file")
      checksums["$platform/install/$basename_file"]="$checksum"
      echo "  $platform/install/$basename_file: $checksum"
    fi
  done
done

echo ""
echo "=== Updating run-remote-steps.sh ==="

# Create the new SHA256 block
cat > /tmp/sha256_block.txt << 'EOF'
# BEGIN SHA256 REPLACEMENT
# SHA256 checksums for all warning and clean scripts across all platforms
# Generated by update-sha256.sh - run that script to regenerate these values
declare -A SHA256=(
EOF

# Add scripts organized by platform
for platform in "${PLATFORMS[@]}"; do
  echo "  # $platform platform" >> /tmp/sha256_block.txt
  
  # Add warning scripts for this platform
  for file in "$platform/install"/*-warnings.sh; do
    if [[ -f "$file" ]]; then
      basename_file=$(basename "$file")
      full_path="$platform/install/$basename_file"
      if [[ -n "${checksums[$full_path]:-}" ]]; then
        echo "  [\"$full_path\"]=\"${checksums[$full_path]}\"" >> /tmp/sha256_block.txt
      fi
    fi
  done
  
  # Add clean scripts for this platform
  for file in "$platform/install"/*-clean.sh; do
    if [[ -f "$file" ]]; then
      basename_file=$(basename "$file")
      full_path="$platform/install/$basename_file"
      if [[ -n "${checksums[$full_path]:-}" ]]; then
        echo "  [\"$full_path\"]=\"${checksums[$full_path]}\"" >> /tmp/sha256_block.txt
      fi
    fi
  done
  
  echo "" >> /tmp/sha256_block.txt
done

echo ")" >> /tmp/sha256_block.txt
echo "# END SHA256 REPLACEMENT" >> /tmp/sha256_block.txt

# Find the start and end of the current SHA256 block in run-remote-steps.sh
start_line=$(grep -n "^# BEGIN SHA256 REPLACEMENT" run-remote-steps.sh | cut -d: -f1)
end_line=$(grep -n "^# END SHA256 REPLACEMENT" run-remote-steps.sh | cut -d: -f1)

if [[ -z "$start_line" ]]; then
  echo "Error: Could not find '# BEGIN SHA256 REPLACEMENT' marker in run-remote-steps.sh"
  exit 1
fi

if [[ -z "$end_line" ]]; then
  echo "Error: Could not find '# END SHA256 REPLACEMENT' marker in run-remote-steps.sh"
  exit 1
fi

# Validate that end line comes after start line
if [[ $end_line -le $start_line ]]; then
  echo "Error: End marker (line $end_line) must come after start marker (line $start_line)"
  exit 1
fi

echo "Found SHA256 block from line $start_line to $end_line"

# Safety check: make sure we're not going to truncate the file
total_lines=$(wc -l < run-remote-steps.sh)
if [[ $end_line -ge $total_lines ]]; then
  echo "Error: End line $end_line is beyond file length $total_lines"
  echo "This would truncate the file. Aborting for safety."
  exit 1
fi

# Create a backup
cp run-remote-steps.sh run-remote-steps.sh.backup
echo "Created backup: run-remote-steps.sh.backup"

# Replace the SHA256 block
{
  head -n $((start_line - 1)) run-remote-steps.sh
  cat /tmp/sha256_block.txt
  tail -n +$((end_line + 1)) run-remote-steps.sh
} > run-remote-steps.sh.new

# Verify the new file has reasonable length
new_lines=$(wc -l < run-remote-steps.sh.new)
if [[ $new_lines -lt $((total_lines - 10)) ]]; then
  echo "Error: New file would be too short ($new_lines lines vs original $total_lines)"
  echo "This suggests the replacement would truncate the file. Aborting."
  rm -f run-remote-steps.sh.new
  exit 1
fi

mv run-remote-steps.sh.new run-remote-steps.sh

# Clean up
rm -f /tmp/sha256_block.txt

echo "✓ Updated run-remote-steps.sh with new SHA256 checksums"
echo "✓ Backup saved as run-remote-steps.sh.backup"
echo ""
echo "Summary of checksums by platform:"
for platform in "${PLATFORMS[@]}"; do
  echo "  $platform platform:"
  for file in "$platform/install"/*-warnings.sh "$platform/install"/*-clean.sh; do
    if [[ -f "$file" ]]; then
      basename_file=$(basename "$file")
      full_path="$platform/install/$basename_file"
      if [[ -n "${checksums[$full_path]:-}" ]]; then
        echo "    $full_path: ${checksums[$full_path]}"
      fi
    fi
  done
  echo ""
done
