#!/run/current-system/profile/bin/guile --no-auto-compile -s
!#

;;; update-manifest.scm
;;; Generate manifest with checksums for all Go source files
;;; This lets users verify GitHub CDN has the latest version

(use-modules (ice-9 popen)
             (ice-9 rdelim)
             (ice-9 format)
             (ice-9 ftw)
             (srfi srfi-1))

;;; Configuration

(define manifest-file "SOURCE_MANIFEST.txt")

;;; Helper Functions

(define (file-sha256 filepath)
  "Calculate SHA256 hash of a file using sha256sum (GNU coreutils).
   Returns the hash string or #f on error."
  (let* ((port (open-input-pipe (format #f "sha256sum ~s" filepath)))
         (output (read-line port))
         (status (close-pipe port)))
    (if (and (zero? status) (not (eof-object? output)))
        (car (string-split output #\space))
        #f)))

(define (find-files-recursive directory pattern)
  "Find all files matching pattern in directory recursively.
   Returns a sorted list of file paths."
  (let ((results '()))
    (ftw directory
         (lambda (filepath statinfo flag)
           (cond
            ;; Regular file
            ((eq? flag 'regular)
             (when (string-suffix? pattern filepath)
               (set! results (cons filepath results)))
             #t)
            ;; Skip .git and vendor directories
            ((and (eq? flag 'directory)
                  (or (string-suffix? "/.git" filepath)
                      (string-suffix? "/vendor" filepath)))
             'skip-subtree)
            ;; Continue for other directories
            (else #t))))
    (sort results string<?)))

(define (write-manifest-header port)
  "Write the manifest file header."
  (format port "# Source File Manifest~%")
  (format port "#~%")
  (format port "# Generated by: ./update-manifest.sh~%")
  (format port "#~%")
  (format port "# Use this to verify GitHub's CDN has the latest version:~%")
  (format port "# Compare these checksums with what you see in the raw files on GitHub~%")
  (format port "~%"))

(define (write-file-checksums port files section-header)
  "Write checksums for a list of files to the manifest port."
  (format port "## ~a~%" section-header)
  (format port "~%")
  (for-each
   (lambda (file)
     (let ((hash (file-sha256 file)))
       (when hash
         (format port "~a  ~a~%" hash file))))
   files)
  (format port "~%"))

(define (write-go-source-checksums port)
  "Write checksums for all Go source files."
  (let ((go-files (find-files-recursive "." ".go")))
    (write-file-checksums port go-files "Go Source Files")))

(define (write-critical-shell-scripts port)
  "Write checksums for critical shell scripts."
  (format port "## Critical Shell Scripts~%")
  (format port "~%")
  
  (let ((scripts '("lib/bootstrap-installer.sh"
                   "lib/clean-install.sh"
                   "lib/verify-guix-install.sh"
                   "lib/recovery-complete-install.sh"
                   "lib/postinstall.sh"
                   "postinstall/lib.sh")))
    (for-each
     (lambda (script)
       (when (file-exists? script)
         (let ((hash (file-sha256 script)))
           (when hash
             (format port "~a  ~a~%" hash script)))))
     scripts))
  
  (format port "~%"))

(define (write-guile-library-scripts port)
  "Write checksums for Guile library scripts."
  (format port "## Guile Library Scripts~%")
  (format port "~%")
  
  (let ((scripts '("lib/guile-config-helper.scm"
                   "lib/bootstrap-postinstall.scm")))
    (for-each
     (lambda (script)
       (when (file-exists? script)
         (let ((hash (file-sha256 script)))
           (when hash
             (format port "~a  ~a~%" hash script)))))
     scripts))
  
  (format port "~%"))

(define (find-customize-scripts)
  "Find all postinstall/customize scripts.
   Returns a sorted list of paths."
  (let ((results '()))
    (ftw "."
         (lambda (filepath statinfo flag)
           (cond
            ((and (eq? flag 'regular)
                  (string-suffix? "/postinstall/customize" filepath))
             (set! results (cons filepath results))
             #t)
            ;; Skip .git directory
            ((and (eq? flag 'directory)
                  (string-suffix? "/.git" filepath))
             'skip-subtree)
            (else #t))))
    (sort results string<?)))

(define (write-postinstall-customization-scripts port)
  "Write checksums for platform-specific customization scripts."
  (format port "## Post-Install Customization Scripts~%")
  (format port "~%")
  
  (let ((customize-scripts (find-customize-scripts)))
    (for-each
     (lambda (script)
       (let ((hash (file-sha256 script)))
         (when hash
           (format port "~a  ~a~%" hash script))))
     customize-scripts))
  
  (format port "~%"))

(define (run-hash-to-words hash)
  "Run hash-to-words program to convert hash to human-readable words.
   Returns the words string or #f if the program fails."
  (let* ((cmd (format #f "go run cmd/hash-to-words/main.go ~s 2>/dev/null" hash))
         (port (open-input-pipe cmd))
         (output (read-line port))
         (status (close-pipe port)))
    (if (and (zero? status) (not (eof-object? output)))
        output
        #f)))

(define (extract-first-last-words words-string n)
  "Extract first N and last N words from a space-separated string.
   Returns a string like 'word1 word2 word3 ... word-n2 word-n1 word-n'."
  (let* ((words (string-split words-string #\space))
         (word-count (length words)))
    (if (< word-count (* 2 n))
        words-string
        (let* ((first-n (take words n))
               (last-n (take-right words n))
               (first-str (string-join first-n " "))
               (last-str (string-join last-n " ")))
          (format #f "~a ... ~a" first-str last-str)))))

(define (display-verification-instructions manifest-hash manifest-words)
  "Display instructions for verifying the manifest checksum."
  (display "================================================================\n")
  (display "MANIFEST CHECKSUM (verify this on Guix ISO before running):\n")
  (display "\n")
  (format #t "  Hash: ~a~%" manifest-hash)
  
  (when manifest-words
    (format #t "  Words: ~a~%" manifest-words)
    (let ((quick-words (extract-first-last-words manifest-words 3)))
      (format #t "  Quick: ~a~%" quick-words)))
  
  (display "\n")
  (display "On Guix ISO, verify with:\n")
  (display "  curl -fsSL https://raw.githubusercontent.com/durantschoon/cloudzy-guix-install/main/SOURCE_MANIFEST.txt | sha256sum\n")
  
  (when manifest-words
    (display "\n")
    (display "Or verify with words (easier to read aloud):\n")
    (display "  curl -fsSL https://raw.githubusercontent.com/durantschoon/cloudzy-guix-install/main/SOURCE_MANIFEST.txt | sha256sum | awk '{print $1}' | ./hash-to-words\n"))
  
  (display "\n")
  (display "If checksums match, GitHub CDN has the latest version.\n")
  (display "================================================================\n")
  (display "\n"))

;;; Main Logic

(define (generate-manifest)
  "Generate the complete source manifest file."
  (display "=== Generating source manifest ===\n")
  
  ;; Write manifest file
  (call-with-output-file manifest-file
    (lambda (port)
      (write-manifest-header port)
      (write-go-source-checksums port)
      (write-critical-shell-scripts port)
      (write-guile-library-scripts port)
      (write-postinstall-customization-scripts port)))
  
  (display "\n")
  (format #t "Manifest written to ~a~%" manifest-file)
  (display "\n")
  
  ;; Calculate and display manifest checksum
  (let* ((manifest-hash (file-sha256 manifest-file))
         (manifest-words (and manifest-hash (run-hash-to-words manifest-hash))))
    
    (when manifest-hash
      (display-verification-instructions manifest-hash manifest-words)
      
      ;; Display file checksums
      (display "File checksums:\n")
      (call-with-input-file manifest-file
        (lambda (port)
          (let loop ()
            (let ((line (read-line port)))
              (unless (eof-object? line)
                (display line)
                (newline)
                (loop)))))))))

;;; Entry Point

(generate-manifest)
